### ISSUE TITLE
URL for lookup not working

### ISSUE THREAD

**Issue by inversiondk** [Fogh/CVR-Alfred#6]
Hi, 

Just dowloaded the workflow (great idea by the way). 
However - when I look up an entry - say "Inversion" - and press enter; I just get the following: 

<img width="403" alt="screen shot 2016-06-03 at 23 30 35" src="https://cloud.githubusercontent.com/assets/12465718/15793288/39116ace-29e3-11e6-8d4e-13b22a190739.png">

Has the API changed or? :)

**Comment by inversiondk** [comment]
To answer my own question :) 
I just changed the URL to: https://cvrapi.dk/api?search={query}&country=dk in the workflow configuration and everything seems to be working fine again. 

Might want to update the code though :)

**Comment by Fogh** [comment]
I wouldn't mind a pull request that fixes this
